apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analysis-process-virus-maven-local-repo
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 