

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
 name: analysis-core-main-listener-interceptor
spec:
 serviceAccountName: pipeline
 triggers:
   - name: GitHub-listener
     bindings:
       - ref: analysis-core-git-pull-request-pipeline-binding
     template:
       name: analysis-core-trigger-promote-pipeline-template





---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
 name: analysis-core-git-pull-request-pipeline-binding
spec:
 params:
 - name: gitrepository
   value: $(body.repository.full_name)
 - name: gitid
   value: $(body.after)




---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
 name: analysis-core-trigger-promote-pipeline-template
spec:
 params:
 - name: gitrepository
 - name: gitid
 resourcetemplates:
 - apiVersion: tekton.dev/v1beta1
   kind: PipelineRun
   metadata:
     generateName: promote-analysis-core-
     namespace: analysis-cicd
     labels:
       app: analysis-core
       tekton.dev/pipeline: analysis-promote-pipeline
   spec:
     params:
       - name: PROJECT_PROD
         value: analysis-prod
       - name: registry-image-tag-name
         value: $(tt.params.gitid)
       - name: git-repository
         value: http://gitea:3000/$(tt.params.gitrepository)
       - name: registry-repository
         value: myregistry-quay-app.analysis-cicd.svc:443/quayadmin/analysis-core
       - name: app-name
         value: analysis-core
       - name: title
         value: "Pull-request for revision id $(tt.params.gitid)"
     pipelineRef:
       name: analysis-promote-pipeline
     serviceAccountName: pipeline
     timeout: 1h0m0s
     workspaces:
       - name: shared-workspace
         persistentVolumeClaim:
           claimName: analysis-core-shared-workspace-promote
       - configMap:
           name: maven-settings
         name: maven-settings
       - name: maven-local-repo
         persistentVolumeClaim:
           claimName: analysis-core-maven-local-repo


