apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analysis-gateway-shared-workspace-build
  namespace: analysis-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
