apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: promote-analysis-gateway
  labels:
    app: analysis-gateway
spec:
  params:
    - default: latest
      description: Image Tag Value
      name: IMAGE_TAG
      type: string
    - default: quay.io/luisarizmendi/analysis-gateway
      name: registry-repository
      type: string
    - default: latest
      name: registry-image-tag-name
      type: string
    - default: webhook-secret
      description: webhook secret name
      name: webhook-secret
      type: string
  resources:
    - name: app-git
      type: git
    - name: image
      type: image
  tasks:
    - name: push-analysis-gateway-image-to-registry
      params:
        - name: registry-repository
          value: $(params.registry-repository)
        - name: registry-image-tag-name
          value: $(params.registry-image-tag-name)
      resources:
        inputs:
          - name: image
            resource: image
      taskRef:
        kind: Task
        name: push-analysis-gateway-image-to-registry
    - name: send-to-webhook-slack
      params:
        - name: webhook-secret
          value: $(params.webhook-secret)
        - name: message
          value: >-
            Pipeline image build waiting to be reviewed 
            $(params.registry-repository):$(params.registry-image-tag-name)
      runAfter:
        - push-analysis-gateway-image-to-registry
      taskRef:
        kind: Task
        name: send-to-webhook-slack
  workspaces:
    - name: shared-workspace





